language: "zh-CN"

reviews:
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  auto_review:
    enabled: true
    drafts: false
    allowed_base_branches:
      - ".*"

chat:
  auto_reply: true
