export const LAYOUT_PREVIEW_HOVER_DELAY_MS = 300;
export const BROWSE_LAYOUT_FADE_DELAY_MS = 120;
export const COLUMN_HIDE_INTENT_DISTANCE_PX = 44;
export const COLUMN_GAP_PX = 8;
export const TRAY_RESTORE_HEADER_BUFFER_PX = 24;
export const TRAY_DRAG_MOVE_THRESHOLD_PX = 3;
export const COLUMN_MENU_WIDTH_PX = 208;
export const COLUMN_MENU_EDGE_GUARD_PX = 8;
export const COLUMN_MENU_TRIGGER_GAP_PX = 4;
export const RESTORE_FLASH_ANIMATION_MS = 1000;
export const RESTORE_FLASH_DELAY_MS = 50;
export const RESTORE_FLASH_DURATION_MS = RESTORE_FLASH_ANIMATION_MS + RESTORE_FLASH_DELAY_MS;

export const LAYOUT_EDIT_CSS_VARS = {
  columnMenuWidth: `${COLUMN_MENU_WIDTH_PX}px`,
  restoreFlashAnimation: `${RESTORE_FLASH_ANIMATION_MS}ms`,
  restoreFlashDelay: `${RESTORE_FLASH_DELAY_MS}ms`,
} as const;
