export const DEFAULT_MAX_AGENT_STEPS = 6;
export const MAX_GENERIC_TOOL_SUCCESS_RESULT_BYTES = 64 * 1024;
export const MAX_GENERIC_TOOL_ERROR_RESULT_BYTES = 4 * 1024;
export const MAX_TOOL_RESULT_BYTES = 8 * 1024;
export const MAX_TURN_TOOL_RESULT_BYTES = 16 * 1024;
